#!/bin/sh /etc/rc.common
#
# Copyright (c) 2016 Arduino Srl
# This file is part of Arduino Ciao.
#
# Starts neard
#

START=53
STOP=53

NAME=neard
DAEMON=/usr/bin/$NAME

# Exit gracefully if the package has been removed
[ -x $DAEMON ] || exit 0

start () {
    echo -n "Starting $NAME: "
    start-stop-daemon -S -q -p /var/run/${NAME}.pid -x $DAEMON -- -d '*'
    echo "OK"
}

stop () {
    echo -n "Stopping $NAME: "
    start-stop-daemon -K -q -p /var/run/${NAME}.pid
    echo "OK"
}

restart () {
    $0 stop
    sleep 1
    $0 start
}

reload () {
    $0 stop
    sleep 1
    $0 start
}
